version: '2'
services:
  api:
    build: api
    volumes:
      - "./api/app:/src/app"
      - "./api/config:/src/config"
      - "./api/custom_typings:/src/custom_typings"
    ports:
      - "3000:3000"
    depends_on:
     - db
  db:
    image: mongo:3.3.6
    ports:
      - "27017:27017"
